### ISSUE TITLE
Change Vim Theme to heliotrope, so relevant info be visible

### ISSUE THREAD

**Issue by hbto** [Vauxoo/docker-odoo-image#106]
Before heliotrope theme
<img width="1440" alt="vim_before" src="https://cloud.githubusercontent.com/assets/7598010/14720789/f02bf794-07cc-11e6-9689-41c0dddcdd24.png">

After heliotrope theme
<img width="1440" alt="vim_after" src="https://cloud.githubusercontent.com/assets/7598010/14720794/f81959ce-07cc-11e6-8349-ef6cc9ba1b5d.png">

**Comment by osvalr** [comment]
what filetypes are supported? does XML get syntax-highlighted?

**Comment by hbto** [comment]
@osvalr 

Before
<img width="1440" alt="vim-xml-before" src="https://cloud.githubusercontent.com/assets/7598010/14728218/a1676334-07fc-11e6-9a8c-f714e680d8ed.png">

After
<img width="1440" alt="vim-xml-after" src="https://cloud.githubusercontent.com/assets/7598010/14728226/a82e99a8-07fc-11e6-910a-b80754b42b10.png">

**Comment by LuisAlejandro** [comment]
When you reach an agreement about this, i can take care of it.

You should bring other people to discuss on whether they like this theme or
not.

Greetings!

**Comment by hbto** [comment]
+1 @LuisAlejandro

**Comment by LuisAlejandro** [comment]
@moylop260 @ruiztulio @nhomar what do you think of this request? no one has commented.

**Comment by zaoral** [comment]
I think is required.
when trying to select lines inside a xml file the selection lines get black and nothing can be read, same as comments inside files.

I think this should be solved.
I think this theme is a good idea

Best Regards

**Comment by moylop260** [comment]
Let's try
Who make the PR?

**Comment by LuisAlejandro** [comment]
I included the change here https://github.com/Vauxoo/docker-odoo-image/pull/105/commits/5cadcb403d5046b30395518d49bc5ef558acaa15
When #105 is merged it should be done.

**Comment by LuisAlejandro** [comment]
To test locally before the merge of #105:

Log into the shippable image:
```
docker run -it vauxoo/odoo-80-image-shippable-auto bash
```
Change the line 1252 of `/root/.vimrc`:
```diff
- colorscheme ir_black
+ colorscheme heliotrope
```
Restart vim.

**Comment by hbto** [comment]
@LuisAlejandro 

Oh!! +1
