### ISSUE TITLE
Build each Dockerfile of this repo in different Travis jobs

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#107]
I suggest that each Dockerfile to be built on Travis is done in different jobs through the use of the matrix feature of `.travis.yml`. This way we can better determine which build failed and also the builds are done in parallel.

**Comment by ruiztulio** [comment]
:+1:

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/docker-odoo-image/issues/104
