### ISSUE TITLE
Make Travis push the images to the Docker hub if the tests succeed

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#110]
If #109 gets implemented, automated builds on the docker hub will need to be deprecated because a clone of a private repository will fail there. One solution to this problem could be to use Travis builds to push the images to hub.docker.com if they pass all tests (after #111 is done). This can be easily done by storing push credentials in the Travis encrypted tokens.

**Comment by LuisAlejandro** [comment]
I've been implementing this feature on my personal images. Feel free to copy the implementation.

The relevant parts are:

* [Login data](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/.travis.yml#L8-L11) for hub.docker.com (encrypted on `.travis.yml`).
* [A matrix](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/.travis.yml#L20-L39) containing all the images to build.
* [A script](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/build-image.sh) to build the images in the [script section of .travis.yml](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/.travis.yml#L40).
* An `after_success` [script](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/push-image.sh) in [.travis.yml](https://github.com/LuisAlejandro/dockershelf/blob/885dc579641c9618112587831d59d112ced7961c/.travis.yml#L41) that pushes to hub.docker.com.

This last step should probably check for `${TRAVIS_BRANCH} == master` to avoid pushing unstable images from pull requests or other branches.

**Comment by moylop260** [comment]
Thanks!
We are using a new propagate option from hub.docker.com
If we have a image changed from repository then a build is runned from docker hub and propagate the build of children images
