### ISSUE TITLE
Define, conceptualize and document each image

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#112]
These images need to have their purpose documented. Which software should be contained in them?

We have four layers of images:

```
ubuntu > docker-ubuntu-base > odoo-80-image > yoytec
```

or

```
ubuntu > docker-ubuntu-base > odoo-80-image > odoo-shippable
```

It seems to me that one of these images is unnecessary. Or docker-ubuntu-base or odoo-80-image. What do you think? @moylop260 @ruiztulio @nhomar 

This issue should be resolved by providing a good README, and a few wiki pages explaining what software is included in each image and what's its purpose.

**Comment by moylop260** [comment]
@ruiztulio Do you have those README files?

@LuisAlejandro 
I can try explain here
The path  `ubuntu > docker-ubuntu-base > odoo-80-image > yoytec` is used by @ruiztulio for production images.
The path `ubuntu > docker-ubuntu-base > odoo-80-image > odoo-shippable -> travis2docker *` is used by developers for development environment of all projects (yoytec, other customer, other project...).

**Comment by LuisAlejandro** [comment]
@moylop260

Thank you!

**Comment by ruiztulio** [comment]
@moylop260 <https://github.com/moylop260> no, I don't have them
