### ISSUE TITLE
Warning: Unable to get information for locale fr_FR. Information from the default locale (en_US) have been used.

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#118]
Odoo now show the following warning:

`2016-05-16 20:20:44,659 141 WARNING openerp_test openerp.addons.base.res.res_lang: Unable to get information for locale fr_FR. Information from the default locale (en_US) have been used.`

Because unittest run with `fr_FR`

**Comment by moylop260** [comment]
We had this configuration from base image, but now with last changes we don't have it
@LuisAlejandro 
Could you check this configuration please?

**Comment by LuisAlejandro** [comment]
Checking.

**Comment by LuisAlejandro** [comment]
This actually belongs to the ubuntu base, that's where locale is configured.
Correcting there vauxoo/docker-ubuntu-base#16
