### ISSUE TITLE
[QUESTION] What's this line for?

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#130]
Hello

I'm analyzing this script:

https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/files/entrypoint_image#L61

And that line is giving the following error on Travis:

```
sed: can't read /root/*/openerp/cli/server.py: No such file or directory
```

Because the Odoo source is on /.repo_requirements and not on /root/

I'm wondering, is this script up to date? Is it still necessary?

Thanks in advance.

**Comment by moylop260** [comment]
The installation from cache of MQT [create a symlink](https://github.com/Vauxoo/maintainer-quality-tools/blob/4ec71d7c70cafa06324ec0d2f2fccdff50550eaa/travis/travis_install_nightly#L48) but just in `TESTS=1` builds.
If your build is of `LINT` you will see the error.
Then IMHO the fix should be apply the patch just if the folder exists.

Could you help us with that?

**Comment by LuisAlejandro** [comment]
Yeap, cool!

**Comment by LuisAlejandro** [comment]
@moylop260 I have more doubts
I see a lot of  duplicated code in [travis_install_nightly](https://github.com/Vauxoo/maintainer-quality-tools/blob/master/travis/travis_install_nightly) (Installation of things that are already installed in odoo-shippable), this has a purpose or is simply not optimized?

**Comment by moylop260** [comment]
Ok
Clean it and create dummy pr for our customer projects
And review that travis and runbot is working fine

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/docker-odoo-image/pull/173
