### ISSUE TITLE
[BUG] Unused code in /tmp

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#131]
Hello,

Upon inspection at the `odoo-80-image` i've found that the /tmp is not clean after finishing the image, resulting in an extra +660MB.

```
$ docker run -it vauxoo/odoo-80-image bash
root@e753f32b21ce:/# du -hs /*
6.3M	/bin
4.0K	/boot
0	/dev
3.8M	/etc
4.0K	/home
24M	/lib
4.0K	/lib64
4.0K	/media
4.0K	/mnt
4.0K	/opt
0	/proc
7.3M	/root
44K	/run
6.8M	/sbin
4.0K	/srv
0	/sys
663M	/tmp           <<<<<<<<<
921M	/usr
16M	/var
```

I'll be making a PR soon.

**Comment by moylop260** [comment]
Good catch!
Could you check `vauxoo/odoo-80-image-shippable-auto` too?

**Comment by LuisAlejandro** [comment]
Yeap

**Comment by LuisAlejandro** [comment]
It's very weird considering [this line](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo80/scripts/build-image.sh#L102) is on the build script.

**Comment by moylop260** [comment]
What about
```patch
- find /tmp -type f -print0 | xargs -0r rm -rf
+ rm -rf /tmp/*
```

**Comment by LuisAlejandro** [comment]
Yeah, simpler.

The `odoo-80-image-shippable-auto` has the same extra 660MB inherited from `odoo-80-image`.

**Comment by moylop260** [comment]
Yeah, It's it but after remove the tmp folder fom inherited image you should re-build and check again...

**Comment by LuisAlejandro** [comment]
Yeap
