### ISSUE TITLE
Study and refactor entrypoint_image according to different use cases

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-odoo-image#134]
As discussed in #130, currently the /entrypoint_image script outputs the following error when being executed inside the build script of `vauxoo/odoo-80-image-shippable-auto`:

```
sed: can't read /root/*/openerp/cli/server.py: No such file or directory
```

This is because the script expects the odoo codebase to be in `/root` and not in `/.repo_requirements`. The script should be adapted to run both on test and build environments.

**Comment by moylop260** [comment]
The main issue here is a missed validation of `os.environ.get('TESTS') ==1`
Because apply a patch to unuse odoo for LINT=1 with TESTS=0 don't make sense.

Could you help me with the fix in other PR?

**Comment by LuisAlejandro** [comment]
Yeah, of course!

**Comment by osvalr** [comment]
I think that a possible solution should be to have the following:
```bash
cmd = """sed -i "s/== 'root'/== 'force_root'/g" %s/*/*/cli/server.py""" % os.getenv("HOME")  # noqa
```
I mean, replacing `openerp` by a `*`

**Comment by osvalr** [comment]
@moylop260 I'm seeing this is still valid

**Comment by moylop260** [comment]
Thanks @osvalr for the video to reproduce it
[![asciicast](https://asciinema.org/a/69n5b6cqfijy3xhts7dflkcbv.png)](https://asciinema.org/a/69n5b6cqfijy3xhts7dflkcbv)

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/docker-odoo-image/pull/173
