### ISSUE TITLE
Failing tests with Odoo 9.0

### ISSUE THREAD

**Issue by ruiztulio** [Vauxoo/docker-odoo-image#135]
I have a repo in git.vauxoo.com and it uses odoo-shippable image to execute the tests it was green until the image was updated, the checking the logs I realized that for some reason it was using odoo 8.0 instead of 9.0 (the few lasts lines):
![error](http://screenshots.vauxoo.com/tulio/14483917616-u9xHnXmmDK.jpg)

And in the previous one (the is from yesterday):
![green](http://screenshots.vauxoo.com/tulio/14493417616-uIDMCWwVEP.jpg)

We didn't change the tests nor the code because we're testing the CI system.

Also we notice this:
![clone90](http://screenshots.vauxoo.com/tulio/14535717616-0Q6kLqPJSc.jpg)

Compared with the one that was successfully tested:
![good](http://screenshots.vauxoo.com/tulio/14551917616-0XXwTXJibR.jpg)

Regards

**Comment by moylop260** [comment]
@LuisAlejandro 
The issue is with odoo cache process.

We need execute before a fetch to download the required branch.

Could you help us?

**Comment by LuisAlejandro** [comment]
Ok, i'll take a look!

**Comment by LuisAlejandro** [comment]
@ruiztulio why do we use an 8.0 image to test 9.0 code?

**Comment by moylop260** [comment]
@luisAlejandro

The image odoo-shippable is for all odoo versions.
I use this image to run t2d for other no-odoo projects.

This image is similar to https://quay.io/repository/travisci/travis-python

**Comment by ruiztulio** [comment]
@LuisAlejandro as @moylop260 said we use a single image and I repeat what I said [here](https://github.com/Vauxoo/docker-odoo-image/pull/133) if you're going to change something at least you **have to** do it in the top of the previous state, that is, if it was working properly with the 9.0 or the "wired" app versions so it have to continue working that way and then, in a later stage, if you consider that we should use separate test images for every Odoo version, change some package versions or you have any other idea it can be discussed, decided and planned as we see it fit.

ATM we need this image working properly as it was.

Regards.

**Comment by LuisAlejandro** [comment]
Cool, I'll be changing it ASAP.
I apologize for this error, I still have things to learn about our architecture so that i don't miss anything.
Regards.

**Comment by moylop260** [comment]
@LuisAlejandro 
Do you have any news?

**Comment by LuisAlejandro** [comment]
Sorry, no @moylop260. Tomorrow i'll give it a look.

**Comment by moylop260** [comment]
@KarenKawaii 
Could you help us to fix this too late issue?

**Comment by KarenKawaii** [comment]
Roger that @moylop260 
I 'll put up with the information of this issue.

**Comment by moylop260** [comment]
@KarenKawaii 
I think that you should start looking for here: [MQT/travis/travis_install_nightly#L43-L53](https://github.com/Vauxoo/maintainer-quality-tools/blob/824b2fa737ccffc067db1787eac63cb47d4af586/travis/travis_install_nightly#L43-L53)

**Comment by KarenKawaii** [comment]
Thanks for the tip
