### ISSUE TITLE
Odoo-shippable: travis_wait script is missing

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#136]
If you add
`travis_wait travis_run_tests` in your script section of .travis.yml now it doesn't works.

Thanks @hbto

**Comment by moylop260** [comment]
[The previous image had a script just to add compatibility with travis_wait](https://github.com/Vauxoo/docker-odoo-image/blob/316f93a55d057b9975bc2c6bd23f37f9e90b4baf/odoo-shippable/Dockerfile#L128-L130
)

It is used from [.travis.yml](https://github.com/Vauxoo/odoo-afr/blob/9caca07659b92abc8c8bb5b2184ed9dfa41953d8/.travis.yml#L41) to avoid a break build of travis if spent too much time.

For the case of the big image we don't have a break build... just we need process the script like as a `bash`

You can see the full original script [here](https://github.com/travis-ci/travis-build/blob/9d936e7ddc9b2fa88244bc8f435d10655dc688b8/lib/travis/build/templates/header.sh#L112-L149)

We need process a extra optional parameter:
`travis_wait 20 script_file.sh` or `travis_wait script_file.sh`
But our script just is a dummy method to call `script_file.sh` and have double compatibility

**Comment by LuisAlejandro** [comment]
Ok, let me check, this is not working somehow https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/scripts/build-image.sh#L186

**Comment by LuisAlejandro** [comment]
![captura de pantalla de 2016-06-28 00-10-53](https://cloud.githubusercontent.com/assets/324683/16403594/a8b429da-3cc0-11e6-800a-cb565c5621c7.png)
This explains it. Is very weird, i copied exactly.
Wait for the PR shortly.
