### ISSUE TITLE
Git diff highlight

### ISSUE THREAD

**Issue by oscarolar** [Vauxoo/docker-odoo-image#139]
There is a really cool feature called `diff-highlight` it is a [PyPi](https://pypi.python.org/pypi/diff-highlight) package.
after installed it is just question of adding this small piece of setup code on the `~/.gitconfig` file
```
[pager]
    log = diff-highlight | less
    show = diff-highlight | less
    diff = diff-highlight | less

```
this will result in a better console diff like this:

![diff](https://www.evernote.com/l/AFz5nFE-4WVBpJaSR7jQy7PcMEBS7jqKStUB/image.png)
Hope we all agree in adding this feature.

**Comment by hugho-ad** [comment]
:+1:

**Comment by LuisAlejandro** [comment]
I agree but i recommend the configuration to be put as global (for all image users) in `/etc/gitconfig` instead of `${HOME}/.gitconfig`.

Regards.

**Comment by moylop260** [comment]
👍

**Comment by zaoral** [comment]
+1
