### ISSUE TITLE
Listed packages in PIP_DEPENDS_EXTRA are not being installed

### ISSUE THREAD

**Issue by ruiztulio** [Vauxoo/docker-odoo-image#152]
As commented in #151 those packages are not being installed, here is another example:

![a](http://screenshots.vauxoo.com/tulio/19531923916-2ymWeHEav4.jpg)

And the package is listed [here](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo80/scripts/build-image.sh#L66)

**Comment by moylop260** [comment]
@KarenKawaii 
Could review it?
