### ISSUE TITLE
Allow use bash script multiple users

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#186]
Currently we have 2 users: shippable and root.
`root` user has all bash configured done.
`shippable` user hasn't bash configured correctly. (bash colors don't work, GIT_STATUS=1...)

We need propagate the bash configuration to all users (not just hardcoded for root and shippable, if other user is created this one should use same bash scripts)

**Comment by LuisAlejandro** [comment]
This is because of using per-user configuration like, for example, `/root/.bashrc` instead of wide-system configuration like `/etc/bash.bashrc` @JesusZapata

**Comment by LuisAlejandro** [comment]
Or `~/.bashrc`, which is expanded to `/root/.bashrc` if the script is run by the `root` user.
