### ISSUE TITLE
Fix when t2d trying to remove pip dependencies with odoo user

### ISSUE THREAD

**Issue by mapuerta** [Vauxoo/docker-odoo-image#195]
When trying to create a container with travisfile2dockerfile using user **odoo** and image **vauxoo/odoo-80-image-shippable-auto**

![execute_command](https://cloud.githubusercontent.com/assets/16363083/23050641/0a01eb1e-f49a-11e6-8752-f13193eda441.png)

Running the build runs an error when you try to uninstall the dependencies
![execute_1](https://cloud.githubusercontent.com/assets/16363083/23050779/bf604ad2-f49a-11e6-91e4-30ec6f05d94e.png)
![error_uninstall_pip](https://cloud.githubusercontent.com/assets/16363083/23050784/c4fe3f94-f49a-11e6-943a-7dde10169182.png)

**Comment by moylop260** [comment]
To reproduce it easiest:
`docker run --user=odoo -it --rm vauxoo/odoo-80-image-shippable-auto pip uninstall -y astroid`
