### ISSUE TITLE
[REF] odoo-shippable: Allow start ssh for "odoo" user

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#202]
Currently running the following command:
`docker run --rm -it --user=odoo vauxoo/odoo-80-image-shippable-auto /etc/init.d/ssh start`

Show the following error:
`mkdir: cannot create directory ‘/var/run/sshd’: Permission denied`

Currently, odoo is not a sudoers user and It can't run `sudo` command.
That is fine.

Now we need a special access to start ssh service for odoo user in order to enable it from runbot builds.

**Comment by moylop260** [comment]
@ruiztulio 
Any clue?

Can help us `supervisor` for this focus?

**Comment by ruiztulio** [comment]
@moylop260 Yes, the only point where you need to be root is to start supervisor, then it can start any service you configure here, maybe started in the entry point, but the supervisor process have to start as root

**Comment by moylop260** [comment]
I got it
Thanks

**Comment by moylop260** [comment]
We are looking for if is posible start the ssh service from runbot using `docker exec -it --user=root CONTAINER_ID /etc/init.d/ssh start`

**Comment by moylop260** [comment]
This feature will be worked from https://github.com/Vauxoo/runbot-addons/pull/93
