### ISSUE TITLE
[REF] odoo-shippable: Slow vim open

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#207]
Running 
`vim -V12log /.repo_requirements/odoo/addons/account/models/account.py`

Output
```bash
"/.repo_requirements/odoo/addons/account/models/account.py" 814L, 44878C
[sy] Register new file.
[sy:git] get_diff_start()   #  <<<<<<-------- Too slow
/.repo_requirements/odoo/addons/account/models

/root/.vim
[sy:git] get_diff_git()
[sy:git] get_diff_end()
[sy:git] set_signs()
[sy:git] No changes found.
[sy:bzr] get_diff_start()
/.repo_requirements/odoo/addons/account/models

/root/.vim
[sy:bzr] get_diff_bzr()
[sy:bzr] get_diff_end()
[sy:hg] get_diff_start()
/.repo_requirements/odoo/addons/account/models

/root/.vim
[sy:hg] get_diff_hg()
[sy:hg] get_diff_end()
/.repo_requirements/odoo/addons/account/models
```

I saw
Slow open file

I expected
Faster open file

Details:
Running:
`rgrep "get_diff_start" . --include=*.vim`

The output is:
```vim
./.vim/bundle/vim-signify/autoload/sy/repo.vim:20:    call sy#repo#get_diff_start(vcs, a:do_register)
./.vim/bundle/vim-signify/autoload/sy/repo.vim:72:" Function: sy#get_diff_start {{{1
./.vim/bundle/vim-signify/autoload/sy/repo.vim:73:function! sy#repo#get_diff_start(vcs, do_register) abort
./.vim/bundle/vim-signify/autoload/sy/repo.vim:74:  call sy#verbose('get_diff_start()', a:vcs)
./.vim/bundle/vim-signify/autoload/sy.vim:77:      call sy#repo#get_diff_start(b:sy.vcs, 0)
```

I mean, the bundle is [vim-signify](https://github.com/mhinz/vim-signify)

I prefer disable by default this bundle in order to open files faster.

**Comment by hbto** [comment]
👍

**Comment by moylop260** [comment]
We had a similar issue about get a `git diff` from https://github.com/Vauxoo/docker-odoo-image/issues/93

The fix was a disable by default and enable from environment variable `GIT_STATUS` https://github.com/Vauxoo/docker-odoo-image/pull/96

Then we could use the same environment variable for the bundle `vim-signify`
I mean, `if GIT_STATUS==1` then enable `vim-signify` bundle (By default disabled)

**Comment by hugho-ad** [comment]
:+1:

**Comment by osvalr** [comment]
:+1: on this

**Comment by zaoral** [comment]
+1 :+1:

**Comment by jorgescalona** [comment]
:+1:

**Comment by JesusZapata** [comment]
@moylop260 
I made `docker pull vauxoo/odoo-80-image-shippable-auto` for download the last imagen for replicate the issue

But the vim open fast 

[![asciicast](https://asciinema.org/a/15ka05a0ooqkrgdjs4d3uh53p.png)](https://asciinema.org/a/15ka05a0ooqkrgdjs4d3uh53p)

**Comment by JesusZapata** [comment]
However I did the PR to disable this functionality

**Comment by ysantiago** [comment]
:thumbsup:

**Comment by moylop260** [comment]
@jesuszapata in your video you had a previous command executed then the git diff was indexed previously.
But if you use the same command from scratch then you will see a opening slowest.
Please review https://github.com/Vauxoo/docker-odoo-image/issues/93 where is the same case.
