### ISSUE TITLE
Add tmux-resurrect to docker odoo image

### ISSUE THREAD

**Issue by tomeyro** [Vauxoo/docker-odoo-image#215]
[tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) is a tmux plugin that allows us to save our tmux environment (`prefix C-s`) and restore it (`prefix C-r`) after we restart our computer.

On top of that, there is also [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) that automatically saves the environment every 15 minutes and restores it when we start tmux.

It would be a nice feature to have by default.

---
CC: @JesusZapata

**Comment by hbto** [comment]
👍

**Comment by hugho-ad** [comment]
:+1:
