### ISSUE TITLE
Error with pylint

### ISSUE THREAD

**Issue by umiphos** [Vauxoo/docker-odoo-image#217]
I created a new container to see if that could solve the problem, but that didn't work.
vauxoo/odoo-80-image-shippable-auto is already up to date.
I'm making a container of this odoo-peru with the branch [10.0-printed_report-umiphos](https://github.com/Vauxoo-dev/odoo-peru/tree/10.0-printed_report-umiphos)
![pylint_error](https://cloud.githubusercontent.com/assets/4094256/24372202/6a6a785e-12ea-11e7-9f30-467eea315b91.png)
This is an image sample of the error, as you can see is just under the call of the pylint.

**Comment by JesusZapata** [comment]
@umiphos 
Could you post the t2d command used?

**Comment by umiphos** [comment]
This is the alias I'm using
```bash
alias t2d="travisfile2dockerfile --root-path=${HOME}/.t2d --run-extra-args='-it --entrypoint=bash -e LANG=en_US.UTF-8 -e START_SSH=1 -m 8g' --add-remote=vauxoo,vauxoo-dev"
```

This is the way I make the container.
```bash
t2d git@github.com:vauxoo-dev/odoo-peru.git 10.0-printed_report-umiphos

/home/umiphos/.t2d/script/git_github.com_vauxoo-dev_odoo-peru.git/10.0-printed_report-umiphos/2/10-build.sh 

docker run --entrypoint=bash -itP --name=odoo-peru_Report vauxoo
```

**Comment by umiphos** [comment]
@JesusZapata  thanks for the answer, that was the problem, my travis2docker was out of date.
