### ISSUE TITLE
[ISSUE] odoo-shippable: postgresql-stats-collector high I/O

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#221]
Since that we are using this database like as demo and temporally to developer environment so we could disable `autovacuum` for odoo-shippable image:
http://edoceo.com/howto/postgresql-stats-collector

**Comment by moylop260** [comment]
@ruiztulio 
What do you think about?

**Comment by ruiztulio** [comment]
@mapuerta vamos a hacer lo siguiente:

1. En la imagen base de [ubuntu](https://github.com/Vauxoo/docker-ubuntu-base) master y agrega un 
 achivo de configuración en ```/etc/postgresql-common/common-vauxoo.conf``` que contenga los parámetros:
 - Que tenemos para [optimizar el postgres](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/templates/Dockerfile.jinja#L18-32) en deployv 
-  Los que comenta @moylop260 en el [enlace](http://edoceo.com/howto/postgresql-stats-collector) 
-  Toma en cuenta que [este](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/templates/Dockerfile.jinja#L25) cambio es en ```pg_hba.conf```

2. En la imagen de odoo80 y odoo100 instala Postgres 9.6 y agrégale al final de ```/etc/postgresql/${PSQL_VERSION}/main/postgresql.conf``` :

```bash
include = '/etc/postgresql-common/common-vauxoo.conf'
```

Ahora con eso tendremos postgres disponible en todas las imágenes con los parámetros de configuración comunes y optimizados para desarrollo y pruebas.

3. En el MR que estás atendiendo [aquí ](https://git.vauxoo.com/vauxoo/deployv/merge_requests/216) elimina la instalacion de postgres porque ya estará en la imagen base


Debes ejecutar los pasos en orden para que no encuentres trabas, porque si eliminas la instalación del paso 3, pero aun no se mergea 1 y no tienes los cambios de 2 va a fallar 3.

@moylop260 ¿qué te parece el plan de acción?

**Comment by moylop260** [comment]
+1

**Comment by JesusZapata** [comment]
@moylop260 @ruiztulio @mapuerta 
Tambien existe esta herramienta http://pgtune.leopard.in.ua/ 
Para tenerla en cuenta

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio Los paquetes **pgbadger** y **pstats_print2list** se seguiran instalando cuando se  construya la imagen con deployv ?

**Comment by ruiztulio** [comment]
@mapuerta no, también se instalan con postgres en el paso 2
