### ISSUE TITLE
[IMP] Auto requirements update 

### ISSUE THREAD

**Issue by JesusZapata** [Vauxoo/docker-odoo-image#235]
The following files is based in another resource:

- The file https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/10.0-full_requirements.txt is based in https://github.com/odoo/odoo/blob/10.0/requirements.txt
- The file https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo90/scripts/9.0-full_requirements.txt is based in https://github.com/odoo/odoo/blob/9.0/requirements.txt
- The file https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo80/scripts/8.0-full_requirements.txt is based in https://github.com/odoo/odoo/blob/8.0/requirements.txt

What do you think about of made small script in charge auto detected change in `odoo/odoo/blob/BRANCH/requirements.txt `

We could use `https://docs.travis-ci.com/user/cron-jobs/` and add enviroment variable with the one token of github for made commit with the change

This is to avoid cases like https://github.com/Vauxoo/docker-odoo-image/pull/234

@moylop260 
What do you think?

**Comment by moylop260** [comment]
The 8.0, 9.0 and 10.0 images are fine.
The real issue with #234 is odoo-shippable where all versions of odoo are used.
Maybe the fix should be just for odoo-shippable image.
