### ISSUE TITLE
The Variable `$TEST_ENABLE` is not defined by default

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/docker-odoo-image#241]
The environment variable `$TEST_ENABLE` is usually used to enable/disable coverage tests.

Even thought those tests are disabled by default, the variable should be set to '"0"' by default, instead of not being defined at all. This whould make easier to change it's value, because it wouldn't be necessary to remember its exact name.

**Comment by moylop260** [comment]
:+1:
Did you have planned create a new PR?

**Comment by luisg123v** [comment]
no, at least not yet.

**Comment by luisg123v** [comment]
The behavior of `test_enable` is different when it's set to 0/1 than when unset, so I'm closing this issue as predefining a value for this could change that behavior.
