### ISSUE TITLE
Odoo dependencies are not being installed during the test process for saas-15

### ISSUE THREAD

**Issue by ruiztulio** [Vauxoo/docker-odoo-image#261]
@moylop260 @JesusZapata We are having an issue with the saas-15 branch, the requirements don't seem to be installed during the test porocess, we are getting the following error:

![a](http://screenshots.vauxoo.com/tulio/10514121417-WRX0w0snkR.jpg)

But that dependency is in the [requirements.txt](https://github.com/Vauxoo/odoo/blob/saas-15/requirements.txt#L41) file

IFAIK ity should be installed in this section:

![b](http://screenshots.vauxoo.com/tulio/10533521417-XPFIFQVnXb.jpg)

In this line:

```bash
pip install -q --no-binary pycparser -r ${ODOO_PATH}/requirements.txt
```

[This](https://git.vauxoo.com/vauxoo-dev/qualifirst/-/jobs/31700) is the build that is failing.

 I was goint to add the dependency to do something like [this](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/build-image.sh#L16-L19) in the big image, but it should be installed during the test process jus for cases like this where a new dependency is added.

what do you think guys?

**Comment by suniagajose** [comment]
i have the same issue, but with saas-14

**Comment by ruiztulio** [comment]
[Here](https://github.com/Vauxoo/docker-odoo-image/pull/262) are the changes I commented in the original issue, this is the build log before rebasing:

![a](http://screenshots.vauxoo.com/tulio/12273921417-Job50RHHjG.jpg)

**Comment by moylop260** [comment]
Thanks for reporting
I'll fix from https://github.com/Vauxoo/maintainer-quality-tools/pull/224
