### ISSUE TITLE
No branch displayed in the promt

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/docker-odoo-image#282]
sinze eae12b019871 revno

the branch is not longer displayed in the prompt

![image](https://user-images.githubusercontent.com/10233975/32576010-43d5ba10-c49b-11e7-940f-d9fa6e46869b.png)

**Comment by hugho-ad** [comment]
@JesusZapata can you help us, do you have an idea whey this it's happening ?

**Comment by zaoral** [comment]
Confirmed.
This happends to me with big image revno eae12b019871

**NOTE:  It seems like promt works for 11.0 containers, but not for 8.0 containers**
