### ISSUE TITLE
Error when pdb and entripoint.sh

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/docker-odoo-image#288]
In some cases the travis detect errors, that cannot be reproduced when the module tests are executed, then If I try add a pdb in the code, and run the entrypoint.sh, the pdb is detected, but the console fail and cannot debug in the code.

**Comment by luistorresm** [comment]
FYI @moylop260

**Comment by moylop260** [comment]
after the first /entrypoint.sh you will need get the last command odoo-bin executed and run it manually
