### ISSUE TITLE
The variable $PSQL_VERSION is not taken into account when starting PostgreSQL

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/docker-odoo-image#298]
I don't know if this worked, but it seems  to not work anymore:

```
$ pg_lsclusters 
Ver Cluster Port Status Owner Data directory               Log file
9.3 main    5432 down   odoo  /var/lib/postgresql/9.3/main pg_log/postgresql.log
9.5 main    5432 down   odoo  /var/lib/postgresql/9.5/main pg_log/postgresql.log
9.6 main    5432 down   odoo  /var/lib/postgresql/9.6/main pg_log/postgresql.log
10  main    5432 down   odoo  /var/lib/postgresql/10/main  pg_log/postgresql.log
$ echo $PSQL_VERSION 
9.5
$ service  postgresql  start 
 * Starting PostgreSQL 9.3 database server                                                                    [ OK ]
$
```

Debugging a little, I noticed the value of the variable `$PSQL_VERSION` is not retrievable in the init scripts, neither in `/etc/init.d/postgresql`, nor `/usr/share/postgresql-common/init.d-functions`.

If I try to print the variable inside those scripts, nothing is printed, like if it was undefined.

**Comment by moylop260** [comment]
You should use `/etc/init.d/postgresql` start instead.

Using 
 - `docker run -e PSQL_VERSION=9.6 -it --rm vauxoo/odoo-80-image-shippable-auto /etc/init.d/postgresql start`
   - The output was: `Starting PostgreSQL 9.6 database server`

 - `docker run -e PSQL_VERSION=9.5 -it --rm vauxoo/odoo-80-image-shippable-auto /etc/init.d/postgresql start`
   - The output was: `Starting PostgreSQL 9.5 database server`

I'm using the latest build of the image:
```bash
docker pull vauxoo/odoo-80-image-shippable-auto
Using default tag: latest
latest: Pulling from vauxoo/odoo-80-image-shippable-auto
Digest: sha256:01379c9a31a08a47cefd5cab114fc776c7b558b034a7cb6f6ce03835504f8698
Status: Image is up to date for vauxoo/odoo-80-image-shippable-auto:latest
```

**Comment by luisg123v** [comment]
@moylop260 
I don't like such a workaround. Init scripts are not intended to be called directly anymore.

The ideal solution would be to write all variables in `/etc/environment` or so, and source that file from the custom script function. For more info, see [This StackExchange answer](https://unix.stackexchange.com/a/44378).

Another solution could be to remove the `''` from [here](https://github.com/Vauxoo/docker-odoo-image/blob/fbb1859f3628fefbe5d6f7d01f92bedd5468a4e3/odoo-shippable/scripts/build-image.sh#L482) and, instead of using an harcoded `9.3`, take the value set for `$PSQL_VERSION` at that point.

But well, if it's not possible, I could deal with that.

**Comment by moylop260** [comment]
We are using the same WA from travis.
Remeber that our image is a copy of travis one with good and bad practices like as virtualenv and init.d/postgresql script modified

**Comment by luisg123v** [comment]
:+1: I understand, thanks for the explanation.
