### ISSUE TITLE
[shippable] Install ssh in developer images and allow root access

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#31]
If we applied next configuration:
http://askubuntu.com/questions/469143/how-to-enable-ssh-root-access-on-ubuntu-14-04
We will allow use ssh connection to runbot builds, and developer container...

**Comment by hugho-ad** [comment]
Close this issue, pr https://github.com/Vauxoo/docker-odoo-image/pull/32 solves the requirement
https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/Dockerfile#L121-L122
