### ISSUE TITLE
[REF] UPDATE wkhtmltopdf version to 0.12.5

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/docker-odoo-image#323]
In order update and try to fix the issue [Memory limit too low or maximum file number of subprocess reached](https://github.com/odoo/odoo/issues/19160#issuecomment-393160785)

Please update  wkhtmltopdf version to 0.12.5 that was released on June 11, 2018

**Comment by ruiztulio** [comment]
@moylop260 @hugho-ad Remember the last time we changed the wkhtmltopdf version, we had to revert it because it was causing issues eith the reports, the format changed and all that stuff.

AFAIK this is the only thing we should consider with this

**Comment by hugho-ad** [comment]
@ruiztulio 

In order to ensure the points that you mention
How can we test 0.12.5 without changing the stable branch and test in all customers projects?

**Comment by moylop260** [comment]
@ruiztulio 
You are right!
Thank you man

@hugho-ad 
I forgot that MQT supports an environment variable for this case.

Define [WKHTMLTOPDF_VERSION="0.12.5"](https://github.com/Vauxoo/maintainer-quality-tools/blob/31c5575eb00ca22b55b1128fc3b625606948f102/travis/travis_install_nightly#L239) in your .travis.yml (for runbot) and .gitlab-ci.yml (for pipelines)

**Comment by hugho-ad** [comment]
@moylop260 

It couldn't download because the file name changed [1]
and the travis script is trying to get :
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5_linux-generic-amd64.tar.xz 
But the  file is:
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb

I get the new url from here https://gist.github.com/srmds/2507aa3bcdb464085413c650fe42e31d

Regards!
[1] https://runbot.vauxoo.com/runbot/static/build/60214-730-34aab2/logs/job_10_test_base.txt

**Comment by moylop260** [comment]
For now, after run install script download and use mqt folder to put the binary
Could you create a issue for MQT of OCA?
