### ISSUE TITLE
What about to use zsh ( linux shell )

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/docker-odoo-image#35]
I have been using zsh (with [oh-my-zsh!](https://github.com/robbyrussell/oh-my-zsh)) for a while locally after use [Fish](http://fishshell.com/) (another one of its kind) and I think that using it inside a Docker container would be helpful in some cases. Oh-my-zsh! has [plugins](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins) and themes that simplifies terminal look and feel and the use of some packages with auto-completion that its plugins provide.

Very few plugins inside oh-my-zsh!:

Use Locally:
- Docker .. https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#docker

Use internal (inside Docker container)
- git .. https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#git
- Themes .. https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes

I leave here a video as a demo of it.
[![Getting Started with ZSH](http://img.youtube.com/vi/1S3MUVIAieE/0.jpg)](http://www.youtube.com/watch?v=1S3MUVIAieE)

**Comment by moylop260** [comment]
Could help me to add a script shell of steps to install for copy&paste them in my container to test it?

**Comment by osvalr** [comment]
@moylop260 there you go,

```bash
# Run docker image
$ docker run -t -i ubuntu:15.04 bash 

# update repos and install needed packages for zsh
$ apt-get update
$ apt-get install wget git zsh

# install oh-my-zsh!
$ sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# and then you can do the following to get into the shell
$ zsh

# ...or do this to change it for your user (https://github.com/robbyrussell/oh-my-zsh#4-change-your-default-shell)
$ chsh -s /bin/zsh
```

all these steps were taken from https://github.com/robbyrussell/oh-my-zsh#getting-started

**Comment by moylop260** [comment]
@osvalr 
If we can decide between bash or zsh IMHO we can add this change to `Dockerfile`
Can you create the PR to [odoo-shippable-Dockerfile](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/Dockerfile)

**Comment by osvalr** [comment]
Hey! @moylop260 here is it https://github.com/Vauxoo/docker-odoo-image/pull/38, please feel free to test it out.. I think that we could make a (starting from an existing one) customized theme with data we may need to show..
