### ISSUE TITLE
[odoo-shippable] ssh: Protocol error: expected packet type 31, got 91 when connecting to odoosh instances

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/docker-odoo-image#385]
Trying to send a file with sync is failing because ssh can establish a connection because of protocol error:
See:

![image](https://user-images.githubusercontent.com/10233975/105231727-edb9d680-5b2c-11eb-9f14-af2fa92ae700.png)

Expected behavior:
Be able to connect with odoosh instances via ssh.

The problem could be  OpenSSL version

See next screenshot from deployv instance
![image](https://user-images.githubusercontent.com/10233975/105232156-9700cc80-5b2d-11eb-898f-fd04cb9339e3.png)

**Comment by fernandahf** [comment]
Hi @hugho-ad 

I researched about this issue and to solve is neccesary to update OpenSSH and OpenSSL versions, this image will be deprecated this year, therefore is not neccesary solve this issue for now, I'm going to close this issue.

Regards.

**Comment by hugho-ad** [comment]
@fernandahf 

but in the meanwhile what's the workaround?
which version shall we install?

**Comment by fernandahf** [comment]
@hugho-ad 

At least OpenSSH v8.0 and OpenSSL v1.1.1.g

Regards.
