### ISSUE TITLE
Validate dockerfile

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/docker-odoo-image#39]
In some point there is a need to validate if a Dockerfile is correctly structured, well there is a package to do that, if Dockerfile files are going to be maintained here.

The following website indicate how to use it
https://www.npmjs.com/package/validate-dockerfile

targeting to **docklint** as the following (using it)
https://github.com/Runnable/validate-dockerfile/blob/master/bin/docklint

Let me know your comments

**Comment by moylop260** [comment]
Could you create a PR to modify the .travis.yml to run this lint?

**Comment by osvalr** [comment]
This issue have been taken in count, so I'll proceed to close it
