### ISSUE TITLE
[BUG] warning msg appears when opening vim inside t2d container

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/docker-odoo-image#65]
message
```bash
"README.md" 187L, 9484C
Could not resolve airline theme "solarized". Themes have been migrated to github.com/vim-airline/vim-airline-themes.
```
screenshot
![docker_error_vim](https://cloud.githubusercontent.com/assets/7593953/12863718/39a38bb4-cc4d-11e5-857f-954c6b54ad03.png)

**Comment by moylop260** [comment]
Fixed here
https://github.com/Vauxoo/docker-odoo-image/pull/66

Thank you for issue
