### ISSUE TITLE
Update git version from 1.9.x to 2.7.x.

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/docker-odoo-image#85]
**Current Behavior**

The current docker version is 1.9.x.
With 1.9.X version it is not available **drop** option in **git rebase -i**

**Expected behavior**

I would like the docker version is updated to 2.7.x
Because in **git rebase -i** it is available **drop** option.

**Comment by yaniaular** [comment]
@moylop260

**Comment by moylop260** [comment]
Fixed here: https://github.com/Vauxoo/docker-odoo-image/pull/86
We will wait that finish the build in https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/
