### ISSUE TITLE
[BUG] vim: open python file do not shows syntax color or do not let to unfold/fold methods

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/docker-odoo-image#88]
Here is a [video](https://youtu.be/u5YxuYDXiF8) demonstration of what is happening.

Some observations:
- This odd behavior show in the video also occurs even if a try to open only one of files.
- No matter if a stop the container and execute it again the behavior maintains.
- This behavior had happen before in other containers a while ago (do not occurs again since today), to me and also to @yaniaular

**Comment by zaoral** [comment]
@moylop260 please can you help me with this issue

**Comment by moylop260** [comment]
@zaoral 
This is a issue of vim tou can fix it with:
`rm -rf ~/.vimviews`

Or you can run 
`rm ~/.vimviews/MYFILE`

@josemoralesp thank you for the information.

**Comment by moylop260** [comment]
FYI tested in the same container of the video:

<img width="923" alt="screen shot 2016-03-16 at 10 47 02 pm" src="https://cloud.githubusercontent.com/assets/6644187/13836641/09578410-ebc9-11e5-9ad9-7e353b8bdea8.png">

**Comment by zaoral** [comment]
Great news!
Thank you @moylop260
