### ISSUE TITLE
Would be nice to add visual indent guides

### ISSUE THREAD

**Issue by gomezvillegasdaniel** [Vauxoo/docker-odoo-image#97]
Like this:
![ ](https://camo.githubusercontent.com/77b20e2e707ac1d85fd8bc12f16b5b7b7e72e186/687474703a2f2f692e696d6775722e636f6d2f4b566930542e6a7067)
For python, javascript and xml

**Comment by moylop260** [comment]
@lescobarvx 
Could you check how add this feature to our big image?

**Comment by lescobarvx** [comment]
@gomezvillegasdaniel 
Currently that feature is in the big image:

![seleccion_003](https://cloud.githubusercontent.com/assets/16093067/14262511/b79a4cdc-fa7f-11e5-9180-0c0303015520.png)

**Comment by moylop260** [comment]
JS file too 
<img width="984" alt="screen shot 2016-04-04 at 3 44 11 pm" src="https://cloud.githubusercontent.com/assets/6644187/14262656/3d182c34-fa7c-11e5-8b3b-be9e5277bfa8.png">
